name: Linux WPT Tests
on:
  push:
    branches: main

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sagudev/bencher repository
        uses: actions/checkout@v4
        with:
           repository: sagudev/bencher
           ref: github-checks
      - name: Install Bencher CLI fork
        run: cargo install --debug --path services/cli --locked --force
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project save-walter-white-1234abcd \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          bencher mock