name: Simple Workflow Test
on:
  push:
    branches: main
permissions:
  checks: write

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    steps:
      - name: Install Bencher CLI fork
        run: cargo install --git https://github.com/sagudev/bencher --branch github-checks --locked --force bencher_cli
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project dklassic-servo \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --adapter json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          bencher mock